database:
  host: ${DB_HOST}
  username: ${DB_USERNAME}
  name: ${DB_NAME}
  port: ${DB_PORT}
  password: ${DB_PASSWORD}

server:
  host: ${SERVER_HOST}
  port: ${SERVER_PORT}

token: 
  tokenExpiresIn: ${TOKEN_EXPIRES_IN}
  tokenMaxAge: ${TOKEN_MAX_AGE}
  tokenSecret: ${TOKEN_SECRET}