version: '1.1'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: ./
    environment:
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_PORT}
      TOKEN_EXPIRES_IN: ${TOKEN_EXPIRES_IN}
      TOKEN_MAX_AGE: ${TOKEN_MAX_AGE}
      TOKEN_SECRET: ${TOKEN_SECRET}
    depends_on:
      - db
    ports:
      - "8082:8081"
    volumes: 
      - ./app:/go/src/app
    
volumes:
  db_data: